workspace_root: &workspace_root
  /go/src/github.com/hashicorp/terraform-google-consul

defaults: &defaults
  working_directory: *workspace_root
  docker:
  - image: gruntwork/circle-ci-test-image-base:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - restore_cache:
          keys:
            - dep-{{ checksum "test/Gopkg.lock" }}
      - run: configure-environment-for-gruntwork-module --go-src-path test --use-go-dep --circle-ci-2
      - save_cache:
          key: dep-{{ checksum "test/Gopkg.lock" }}
          paths:
          - /go/src/github.com/hashicorp/terraform-google-consul/test/vendor
      - persist_to_workspace:
          root: *workspace_root
          paths: test/vendor
  test:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV
      - attach_workspace:
          at: *workspace_root
      - run: run-go-tests --circle-ci-2 --path test

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test